hot_dog:
    resource: "@HotDogBundle/Resources/config/routing.yml"
    prefix:   /

mm_project:
    resource: "@MMProjectBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
